### ISSUE TITLE
nav cleanup on Institute

### ISSUE THREAD

**Issue by mattkirkland** [brandnewbox/bnb_blazer#17]
We've got this running on https://staging.institutefsp.org/bnbintel/ (log in w matt's admin credentials in 1pass)

BUT the nav is kind of screwed up. Let's: 
- visit every page / screen and audit what's happening with the nav. Document this.
- - pay attention to mobile, we've got this kind of working in some places and not in other
- make a proposal for how to clean this up and make it standard (like: the same stuff is always in the navigation!)

**Comment by monicacan** [comment]
Here is [what I documented from the audit](https://www.figma.com/file/U5sUxTQGp1LANPFNNAzSkz/Institute?node-id=7070%3A61663&t=qd1fneTzuznuGofi-1). 

I have some questions before making a proposal:
- Is this site using the bootstrap library? 
- I saw 2 versions of the Nav bar. One showing "new query" and one showing "home" on the dropdown menu. Is this intentional or can I suggest they both say the same thing?

![image](https://user-images.githubusercontent.com/84332926/224183735-c00baa6f-b5d4-4949-af3d-6b5b6f966f19.png)

![image](https://user-images.githubusercontent.com/84332926/224183771-078c596e-ed30-4aed-8a0d-decad2d95f75.png)

- On the mobile version, there are 3 links in the hamburger menu that don't appear on the desktop (Check's Test Dashboard, Dashboard Part Deux, User growth). Is this also intentional or do we make it the same on desktop?

![image](https://user-images.githubusercontent.com/84332926/224184152-d90b2f1a-5aa6-4120-8f79-a12384490a2b.png)

- Some pages don't have a nav bar at all. Is this intentional or can we add the nav bar for those as well?

**Comment by mattkirkland** [comment]
- we can rethink the whole nav, that inconsistency between 'home' and 'new query' is definitely something to be improved.
- it's using Bootstrap v3.3.7, an old one
- Those sidebar links are 'dashboards' - you can see them in the list that shows up

**Comment by monicacan** [comment]
thanks! Are the 'dashboards' supposed to be pinned to the menu? Or can I find another place for them? @mattkirkland

**Comment by mattkirkland** [comment]
I think the key is that they should be QUICKLY accessible - we want a CEO-level person to have stats about their app at their fingertips, and the dashboard function is the most direct way there

**Comment by monicacan** [comment]
Here is[ the Figma file with my audit and suggestions](https://www.figma.com/file/U5sUxTQGp1LANPFNNAzSkz/Institute?node-id=7070%3A61663&t=zagaQtycA0AAUcw8-1)

**Comment by monicacan** [comment]
Did you have any comments for this? @mattkirkland

**Comment by monicacan** [comment]
Poking @mattkirkland! What should be the next steps for this? Do you want me to pick a version and prepare it for handoff?

**Comment by mattkirkland** [comment]
Closing this because I want @vikascripps to take a fresh look
